#!/usr/bin/env node
'use strict';

var TerminalAdapter = require('yeoman-environment/lib/adapter.js');
var yeoman = require('yeoman-environment');
var path = require('path');
var Promise = require('promise');
var argv = require('minimist')(process.argv.slice(2));

class CreateSuppressingTerminalAdapter extends TerminalAdapter {
    constructor() {
        super();
        // suppress 'create' output generated by yeoman
        this.log.create = function() {};
    }
}

function init(argsOrName) {
    console.log('Initializing new Polymer Native app');
    var env = yeoman.createEnv(
        undefined,
        undefined,
        new TerminalAdapter()
    );

    env.register(
        require.resolve(path.join(__dirname, 'ios-generator/app')),
        'ios-generator:app'
    );

    // argv is for instance
    // ['node', 'react-native', 'init', 'AwesomeApp', '--verbose']
    // args should be ['AwesomeApp', '--verbose']
    var args = Array.isArray(argsOrName)
        ? argsOrName
        : [argsOrName].concat(process.argv.slice(4));

    var generator = env.create('ios-generator:app', {args: args});
    generator.destinationRoot('./');
    generator.run();
}

var args = process.argv.slice(3);

if (argv._ && argv._.indexOf('init') > -1) {
    console.log(argv._[1]);
    init(args);
}